# Generated by Django 4.0.5 on 2022-08-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsletter',
            new_name='NewsLetters',
        ),
        migrations.RenameModel(
            old_name='NewsletterUser',
            new_name='UserNewsLetter',
        ),
    ]
