# Generated by Django 4.0.5 on 2022-06-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productos',
            table='productos',
        ),
    ]
