# Generated by Django 4.0.5 on 2022-07-12 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_categoria_rename_productos_producto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Marca',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_relacionados', to='productos.marca'),
        ),
        migrations.AlterModelTable(
            name='marca',
            table='marcas',
        ),
    ]
