# Generated by Django 4.0.5 on 2022-07-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tags',
            field=models.ManyToManyField(to='productos.tag'),
        ),
    ]
