# Generated by Django 4.0.5 on 2022-07-12 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_producto_tags'),
        ('productos', '0010_tag_producto_tags'),
    ]

    operations = [
    ]
