# Generated by Django 4.0.5 on 2022-07-12 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_merge_0009_producto_tags_0010_tag_producto_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
