# Generated by Django 4.0.5 on 2022-07-15 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0013_tag_productotag_producto_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='favorito',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
