# Generated by Django 4.0.5 on 2022-07-15 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0014_producto_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='favorito',
            field=models.ManyToManyField(blank=True, related_name='favorito', to=settings.AUTH_USER_MODEL),
        ),
    ]
